### ISSUE TITLE
My scheduled job does not run when app is closed

### ISSUE THREAD

**Issue by jagan999** [talkdirty/android_job_scheduler#6] opened 2018-06-26 14:02 UTC
On my native Android app, I achieved this by having a foreground service that keeps running and persistent across reboots. I don't think this is possible. Please clarify

**Comment by talkdirty** [comment] 2018-06-26 14:48
Hey there. This is entirely possible. As this Plugin basically passes data on to the JobScheduler API, please refer to the JobScheduler Documentation here: https://developer.android.com/topic/performance/scheduling

As to why your Job is not running, can you reproduce this with the example App?

**Comment by talkdirty** [comment] 2018-07-05 08:09
I'm closing this since the OP is not responding

**Closed by talkdirty** 2018-07-05 08:09 UTC
